// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnU2JN3lz8T38EKW0ATZhWNWJc1nRj4BI',
    appId: '1:901569135151:web:9a418547fd02e5d951fcda',
    messagingSenderId: '901569135151',
    projectId: 'mobility-app-3a812',
    authDomain: 'mobility-app-3a812.firebaseapp.com',
    storageBucket: 'mobility-app-3a812.firebasestorage.app',
    measurementId: 'G-7GZBHLG9EY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDySAUbQMNIJ0OsfefRQ7j4eIECXhpjZi4',
    appId: '1:901569135151:android:7ff95a529298916951fcda',
    messagingSenderId: '901569135151',
    projectId: 'mobility-app-3a812',
    storageBucket: 'mobility-app-3a812.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq6Yzgd1RhOy-Uik966SDJzKFU679e1zQ',
    appId: '1:901569135151:ios:88f13f62d151c9a451fcda',
    messagingSenderId: '901569135151',
    projectId: 'mobility-app-3a812',
    storageBucket: 'mobility-app-3a812.firebasestorage.app',
    iosBundleId: 'com.example.mobilityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq6Yzgd1RhOy-Uik966SDJzKFU679e1zQ',
    appId: '1:901569135151:ios:88f13f62d151c9a451fcda',
    messagingSenderId: '901569135151',
    projectId: 'mobility-app-3a812',
    storageBucket: 'mobility-app-3a812.firebasestorage.app',
    iosBundleId: 'com.example.mobilityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnU2JN3lz8T38EKW0ATZhWNWJc1nRj4BI',
    appId: '1:901569135151:web:a768d432fea972ad51fcda',
    messagingSenderId: '901569135151',
    projectId: 'mobility-app-3a812',
    authDomain: 'mobility-app-3a812.firebaseapp.com',
    storageBucket: 'mobility-app-3a812.firebasestorage.app',
    measurementId: 'G-L96R1T3Z74',
  );
}
